export const influencers = [
  {
    name: "John Snow",
    location: "Washington DC, USA",
    followers: "350k",
    price: "$350k",
    img: "./images/portrait3.jpg",
    category: "Fitness",
    bgColor: "rgba(75, 188, 58,0.1)",
    color: "rgba(75, 188, 58,1)",
  },
  {
    name: "Jennifer Lopez",
    location: "Chicago, USA",
    followers: "350k",
    price: "$250k",
    img: "./images/portrait5.jpg",
    category: "Music",
    bgColor: "rgba(13, 91, 225,0.1)",
    color: "rgba(13, 91, 225,1)",
  },
  {
    name: "Luca Sabaat",
    location: "New York, USA",
    followers: "450k",
    price: "$350k",
    img: "./images/portrait3.jpg",
    category: "Model",
    bgColor: "rgba(221, 0, 4,0.1)",
    color: "rgba(221, 0, 4,1)",
  },
  {
    name: "Marsai Martin",
    location: "Lagos, NG",
    followers: "550k",
    price: "$650k",
    img: "./images/selfie1.jpg",
    category: "Lifestyle",
    bgColor: "rgba(255, 53, 184,0.1)",
    color: "rgba(255, 53, 184,1)",
  },
];
